import Carousel from './Carousel.vue';
import CarouselViewport from './CarouselViewport.vue';
import CarouselSlider from './CarouselSlider.vue';
import CarouselCard from './CarouselCard.vue';
import CarouselButton from './CarouselButton.vue';
import CarouselAutoplayButton from './CarouselAutoplayButton.vue';
import CarouselNav from './CarouselNav.vue';
import CarouselNavButton from './CarouselNavButton.vue';
import CarouselNavImageButton from './CarouselNavImageButton.vue';
import CarouselNavContainer from './CarouselNavContainer.vue';
export const FCarousel = Carousel;
export const FCarouselViewport = CarouselViewport;
export const FCarouselSlider = CarouselSlider;
export const FCarouselCard = CarouselCard;
export const FCarouselButton = CarouselButton;
export const FCarouselAutoplayButton = CarouselAutoplayButton;
export const FCarouselNav = CarouselNav;
export const FCarouselNavButton = CarouselNavButton;
export const FCarouselNavImageButton = CarouselNavImageButton;
export const FCarouselNavContainer = CarouselNavContainer;
export * from './Carousel.types';
