import TeachingPopover from './TeachingPopover.vue';
import TeachingPopoverTrigger from './TeachingPopoverTrigger.vue';
import TeachingPopoverSurface from './TeachingPopoverSurface.vue';
import TeachingPopoverHeader from './TeachingPopoverHeader.vue';
import TeachingPopoverTitle from './TeachingPopoverTitle.vue';
import TeachingPopoverBody from './TeachingPopoverBody.vue';
import TeachingPopoverFooter from './TeachingPopoverFooter.vue';
import TeachingPopoverCarousel from './TeachingPopoverCarousel.vue';
import TeachingPopoverCarouselCard from './TeachingPopoverCarouselCard.vue';
import TeachingPopoverCarouselNav from './TeachingPopoverCarouselNav.vue';
import TeachingPopoverCarouselNavButton from './TeachingPopoverCarouselNavButton.vue';
import TeachingPopoverCarouselPageCount from './TeachingPopoverCarouselPageCount.vue';
import TeachingPopoverCarouselFooter from './TeachingPopoverCarouselFooter.vue';
import TeachingPopoverCarouselFooterButton from './TeachingPopoverCarouselFooterButton.vue';
export const FTeachingPopover = TeachingPopover;
export const FTeachingPopoverTrigger = TeachingPopoverTrigger;
export const FTeachingPopoverSurface = TeachingPopoverSurface;
export const FTeachingPopoverHeader = TeachingPopoverHeader;
export const FTeachingPopoverTitle = TeachingPopoverTitle;
export const FTeachingPopoverBody = TeachingPopoverBody;
export const FTeachingPopoverFooter = TeachingPopoverFooter;
export const FTeachingPopoverCarousel = TeachingPopoverCarousel;
export const FTeachingPopoverCarouselCard = TeachingPopoverCarouselCard;
export const FTeachingPopoverCarouselNav = TeachingPopoverCarouselNav;
export const FTeachingPopoverCarouselNavButton = TeachingPopoverCarouselNavButton;
export const FTeachingPopoverCarouselPageCount = TeachingPopoverCarouselPageCount;
export const FTeachingPopoverCarouselFooter = TeachingPopoverCarouselFooter;
export const FTeachingPopoverCarouselFooterButton = TeachingPopoverCarouselFooterButton;
export * from './TeachingPopover.types';
