import type { App, Plugin } from 'vue';
import { FAccordion } from './components/Accordion';
import { FAccordionHeader } from './components/AccordionHeader';
import { FAccordionItem } from './components/AccordionItem';
import { FAccordionPanel } from './components/AccordionPanel';
import { FAvatar } from './components/Avatar';
import { FAvatarGroup } from './components/AvatarGroup';
import { FAvatarGroupItem } from './components/AvatarGroupItem';
import { FAvatarGroupPopover } from './components/AvatarGroupPopover';
import { FBadge } from './components/Badge';
import { FBreadcrumb } from './components/Breadcrumb';
import { FBreadcrumbButton } from './components/BreadcrumbButton';
import { FBreadcrumbDivider } from './components/BreadcrumbDivider';
import { FBreadcrumbItem } from './components/BreadcrumbItem';
import { FButton } from './components/Button';
import { FCard } from './components/Card';
import { FCardFooter } from './components/CardFooter';
import { FCardHeader } from './components/CardHeader';
import { FCardPreview } from './components/CardPreview';
import { FCheckbox } from './components/Checkbox';
import { FCompoundButton } from './components/CompoundButton';
import { FCounterBadge } from './components/CounterBadge';
import { FDivider } from './components/Divider';
import { FField } from './components/Field';
import { FImage } from './components/Image';
import { FInput } from './components/Input';
import { FLabel } from './components/Label';
import { FPresenceBadge } from './components/PresenceBadge';
import { FProgressBar } from './components/ProgressBar';
import { FRadio } from './components/Radio';
import { FRadioGroup } from './components/RadioGroup';
import { FRating } from './components/Rating';
import { FRatingDisplay } from './components/RatingDisplay';
import { FRatingItem } from './components/RatingItem';
import { FSearchBox } from './components/SearchBox';
import { FSelect } from './components/Select';
import { FLink } from './components/Link';
import { FList } from './components/List';
import { FListItem } from './components/ListItem';
import { FSkeleton } from './components/Skeleton';
import { FSkeletonItem } from './components/SkeletonItem';
import { FSlider } from './components/Slider';
import { FSpinner } from './components/Spinner';
import { FSpinButton } from './components/SpinButton';
import { FSwitch } from './components/Switch';
import { FTab } from './components/Tab';
import { FTabList } from './components/TabList';
import { FText } from './components/Text';
import { FTextarea } from './components/Textarea';
import { FToggleButton } from './components/ToggleButton';

export const FluentVue: Plugin = {
  install(app: App) {
    app.component('FAccordion', FAccordion);
    app.component('FAccordionHeader', FAccordionHeader);
    app.component('FAccordionItem', FAccordionItem);
    app.component('FAccordionPanel', FAccordionPanel);
    app.component('FAvatar', FAvatar);
    app.component('FAvatarGroup', FAvatarGroup);
    app.component('FAvatarGroupItem', FAvatarGroupItem);
    app.component('FAvatarGroupPopover', FAvatarGroupPopover);
    app.component('FBadge', FBadge);
    app.component('FBreadcrumb', FBreadcrumb);
    app.component('FBreadcrumbButton', FBreadcrumbButton);
    app.component('FBreadcrumbDivider', FBreadcrumbDivider);
    app.component('FBreadcrumbItem', FBreadcrumbItem);
    app.component('FButton', FButton);
    app.component('FCard', FCard);
    app.component('FCardFooter', FCardFooter);
    app.component('FCardHeader', FCardHeader);
    app.component('FCardPreview', FCardPreview);
    app.component('FInput', FInput);
    app.component('FSelect', FSelect);
    app.component('FCheckbox', FCheckbox);
    app.component('FCompoundButton', FCompoundButton);
    app.component('FCounterBadge', FCounterBadge);
    app.component('FDivider', FDivider);
    app.component('FField', FField);
    app.component('FImage', FImage);
    app.component('FPresenceBadge', FPresenceBadge);
    app.component('FProgressBar', FProgressBar);
    app.component('FRadio', FRadio);
    app.component('FRadioGroup', FRadioGroup);
    app.component('FRating', FRating);
    app.component('FRatingDisplay', FRatingDisplay);
    app.component('FRatingItem', FRatingItem);
    app.component('FSearchBox', FSearchBox);
    app.component('FLabel', FLabel);
    app.component('FLink', FLink);
    app.component('FList', FList);
    app.component('FListItem', FListItem);
    app.component('FSkeleton', FSkeleton);
    app.component('FSkeletonItem', FSkeletonItem);
    app.component('FSlider', FSlider);
    app.component('FSpinner', FSpinner);
    app.component('FSpinButton', FSpinButton);
    app.component('FSwitch', FSwitch);
    app.component('FTab', FTab);
    app.component('FTabList', FTabList);
    app.component('FText', FText);
    app.component('FTextarea', FTextarea);
    app.component('FToggleButton', FToggleButton);
  },
};
