import { defineComponent, h } from 'vue';
import {
  FBadge,
  FButton,
  FCheckbox,
  FCounterBadge,
  FDivider,
  FField,
  FImage,
  FInput,
  FLabel,
  FLink,
  FPresenceBadge,
  FProgressBar,
  FSkeleton,
  FSkeletonItem,
  FSlider,
  FSpinner,
  FSwitch,
  FText,
  FTextarea,
} from '../../src';

export const SsrFixture = defineComponent({
  name: 'SsrFixture',
  setup() {
    return () =>
      h('main', { class: 'fui-theme-light' }, [
        h(FText, { as: 'h1', size: 700 }, () => 'SSR fixture'),
        h(FLabel, { for: 'standalone-input' }, () => 'Standalone input'),
        h(FInput, { id: 'standalone-input', defaultValue: 'Initial value' }),
        h(
          FField,
          {
            label: 'Email address',
            hint: 'Use a work address.',
            required: true,
          },
          { default: () => h(FInput, { type: 'email' }) },
        ),
        h(
          FField,
          { label: 'Biography' },
          { default: () => h(FTextarea, { defaultValue: 'Vue-native components' }) },
        ),
        h(FCheckbox, { defaultChecked: true, label: 'Accept terms' }),
        h(FDivider, { 'aria-label': 'Contentless boundary' }),
        h(FDivider, { appearance: 'brand' }, () => 'Server section'),
        h(FDivider, { vertical: true }, () => 'Vertical section'),
        h(FImage, {
          src: 'data:image/gif;base64,R0lGODlhAQABAAAAACw=',
          alt: 'SSR image',
          fit: 'cover',
          shape: 'rounded',
          width: 64,
          height: 48,
        }),
        h(FBadge, { appearance: 'tint', color: 'success', shape: 'rounded' }, () => 'Server badge'),
        h(FCounterBadge, {
          count: 120,
          overflowCount: 99,
          role: 'img',
          'aria-label': 'Server notifications',
        }),
        h(FPresenceBadge, { status: 'away', outOfOffice: true, size: 'large' }),
        h(FSpinner, { label: 'Server loading', labelPosition: 'before', size: 'large' }),
        h(FSpinner, {
          class: 'ssr-delayed-spinner',
          delay: 1000,
          label: 'Delayed server loading',
        }),
        h(FProgressBar, {
          class: 'ssr-determinate-progress',
          value: 36,
          max: 100,
          thickness: 'large',
          'aria-label': 'Server progress',
        }),
        h(
          FSkeleton,
          {
            class: 'ssr-skeleton',
            animation: 'pulse',
            appearance: 'translucent',
            size: 24,
            shape: 'circle',
            'aria-label': 'Server skeleton',
          },
          { default: () => h(FSkeletonItem, { class: 'ssr-skeleton-item', as: 'span' }) },
        ),
        h(
          FSkeleton,
          {
            class: 'ssr-skeleton-status',
            as: 'span',
            role: 'status',
            'aria-busy': false,
            width: 180,
            'aria-label': 'Server skeleton status',
          },
          { default: () => h(FSkeletonItem) },
        ),
        h(FProgressBar, {
          class: 'ssr-indeterminate-progress',
          'aria-label': 'Server indeterminate progress',
        }),
        h(
          FField,
          {
            label: 'Server field progress',
            hint: 'Rendered with Field context.',
            validationState: 'warning',
            validationMessage: 'Server progress warning',
          },
          { default: () => h(FProgressBar, { class: 'ssr-field-progress', value: 0.75 }) },
        ),
        h(FSlider, {
          class: 'ssr-slider',
          'aria-label': 'Server volume',
          defaultValue: 0.3,
          min: -0.5,
          max: 0.5,
          step: 0.1,
        }),
        h(
          FField,
          {
            label: 'Server slider field',
            hint: 'Server slider hint',
            validationMessage: 'Server slider invalid',
            size: 'small',
          },
          { default: () => h(FSlider, { class: 'ssr-field-slider', vertical: true }) },
        ),
        h(FSwitch, {
          class: 'ssr-switch',
          defaultChecked: true,
          label: 'Server switch',
          labelPosition: 'before',
          name: 'server-switch',
          value: 'enabled',
        }),
        h(
          FField,
          { label: 'Server field switch', hint: 'Server switch hint', required: true },
          { default: () => h(FSwitch, { class: 'ssr-field-switch' }) },
        ),
        h(FLink, { href: '#details' }, () => 'View details'),
        h(FButton, { appearance: 'primary' }, () => 'Continue'),
      ]);
  },
});
